workflows:
  version: 2
  node-multi-build:
    jobs:
      - eslint-v6
      - node-v12
      - node-v14
      - node-v16
      - lint

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test

  eslint-v6:
    docker:
      - image: node:12
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install eslint@6
          command: |
            npm install --save-exact eslint@6.8.0
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
  node-v14:
    <<: *node-base
    docker:
      - image: node:14
  node-v16:
    <<: *node-base
    docker:
      - image: node:16

  lint:
    docker:
      - image: node:14
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run lint
